import { createEnv } from "@t3-oss/env-nextjs"
import { z } from "zod"

export const env = createEnv({
  server: {
    API_ROOT: z.string().url(),
    MOCK_API_ROOT: z.string().url(),
    GRPC_API_ROOT: z.string().url(),
    SPOTIFY_CLIENT_ID: z.string(),
    SPOTIFY_CLIENT_SECRET: z.string(),
    NEXTAUTH_URL: z.string().url(),
    NEXTAUTH_SECRET: z.string(),
    AWS_REGION: z.string(),
    AWS_ACCESS_KEY_ID: z.string(),
    AWS_SECRET_ACCESS_KEY: z.string(),
    COGNITO_USER_POOL_ID: z.string(),
    COGNITO_CLIENT_ID: z.string(),
    COGNITO_CLIENT_SECRET: z.string(),
    COGNITO_ISSUER: z.string().url(),
    COGNITO_DOMAIN: z.string(),
    REDIS_HOST: z.string(),
    REDIS_PORT: z.number(),
    REDIS_PASSWORD: z.string(),
  },
  client: {
    NEXT_PUBLIC_API_ROOT: z.string().url(),
    NEXT_PUBLIC_MOCK_API_ROOT: z.string().url(),
    NEXT_PUBLIC_SPOTIFY_CDN_HOST: z.string(),
  },
  runtimeEnv: {
    API_ROOT: process.env.API_ROOT,
    MOCK_API_ROOT: process.env.MOCK_API_ROOT,
    GRPC_API_ROOT: process.env.GRPC_API_ROOT,
    SPOTIFY_CLIENT_ID: process.env.SPOTIFY_CLIENT_ID,
    SPOTIFY_CLIENT_SECRET: process.env.SPOTIFY_CLIENT_SECRET,
    NEXT_PUBLIC_API_ROOT: process.env.NEXT_PUBLIC_API_ROOT,
    NEXT_PUBLIC_MOCK_API_ROOT: process.env.NEXT_PUBLIC_MOCK_API_ROOT,
    NEXT_PUBLIC_SPOTIFY_CDN_HOST: process.env.NEXT_PUBLIC_SPOTIFY_CDN_HOST,
    NEXTAUTH_URL: process.env.NEXTAUTH_URL,
    NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,
    AWS_REGION: process.env.AWS_REGION,
    AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
    AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
    COGNITO_USER_POOL_ID: process.env.COGNITO_USER_POOL_ID,
    COGNITO_CLIENT_ID: process.env.COGNITO_CLIENT_ID,
    COGNITO_CLIENT_SECRET: process.env.COGNITO_CLIENT_SECRET,
    COGNITO_ISSUER: process.env.COGNITO_ISSUER,
    COGNITO_DOMAIN: process.env.COGNITO_DOMAIN,
    REDIS_HOST: process.env.REDIS_HOST,
    REDIS_PORT: parseInt(process.env.REDIS_PORT, 10),
    REDIS_PASSWORD: process.env.REDIS_PASSWORD,
  },
})
